### ISSUE TITLE
System error at step 3.5

### ISSUE THREAD

**Issue by lwjhussein** [limepepper/ansible-role-raspberrypi#13] opened 2021-08-11 19:56 UTC
I am having challanges with the script using my own image created after updates and setting VNC and autohotspot, the image file created by the script is running out of space and it aborts. 

Anyone know how to change the file sizes to suit a custom image.

**Comment by tolland** [comment] 2021-08-12 07:01
Can you provide the details on what base image you used, and the list of packages added, and I'll see if I can reproduce

**Comment by lwjhussein** [comment] 2021-08-17 23:36
Apologies for the delay in replying. I used the image from https://downloads.raspberrypi.org/raspios_armhf/images/raspios_armhf-2021-05-28/2021-05-07-raspios-buster-armhf.zip


I first run update, then enabled vnc, and installed the script from 

https://www.raspberryconnect.com/projects/65-raspberrypi-hotspot-accesspoints/183-raspberry-pi-automatic-hotspot-and-static-hotspot-installer

After this i ran the script on an image i extracted using pi-tools. That i got from 

https://github.com/Botspot/Pi-Power-Tools

**Comment by tolland** [comment] 2021-09-01 16:59
I guess the first thing I would expect to cause a problem is that if you boot the vanilla image (before the script), then the resize script will run, and the root partition would get resized to fill the disk. (this would probably be filled with zeroes and zip down quite weill, but I've never tried that)

**Comment by tolland** [comment] 2021-09-08 19:31
currently the script is too simple to handle the case that you describe. 

I think it might be possible to do something like starting with a raspOS desktop restore image. Boot the restore image on a physical rPi, make the required changes (updates, wifi, packages), and then either:

1) use the Pi-Power-Tools to extract the image and replace it over the recovery.img.zip file in the recoveryfs partition

or

2) boot to the recoveryfs image (but not restore anything) and then manually extract the rootfs partition to an img file, zip it, and write over the recovery.img.zip file.

I'm going to close this issue, because its not supported atm. But I am going to add a future feature to allow updating the recovery.img.zip file from the current rootfs, which I think would handle this case.

**Closed as completed by tolland** 2021-09-08 19:31 UTC
